[server]
headless = true
# Configuração compatível com proteção XSRF
enableXsrfProtection = true
# Configuração de endereço (a porta será definida pelo Streamlit Cloud)
address = "0.0.0.0"

[browser]
# Configurações do navegador
gatherUsageStats = false

[theme]
primaryColor = "#4F8A10"         # Verde para o tema de suinocultura
backgroundColor = "#262730"      # Fundo escuro
secondaryBackgroundColor = "#0E1117"  # Cor secundária escura
textColor = "#FAFAFA"           # Texto claro para contraste com o fundo escuro
font = "sans serif"
base = "dark"                   # Define o tema base como escuro

[ui]
hideTopBar = false

[runner]
fastReruns = true

[client]
showErrorDetails = true

[logger]
level = "info"

[global]
developmentMode = false